ALTER TABLE Tickets
ALTER COLUMN TicketID INTEGER NOT NULL

ALTER TABLE Tickets
ADD VersionID INTEGER NOT NULL 

ALTER TABLE Tickets
ADD CONSTRAINT UQ_Ticket_version UNIQUE (TicketID, VersionID)